blog/urls.py
from django.urls import path

from .views import *

app_name = 'blog'

urlpatterns = [

    path('', PostListView.as_view(), name='blog-home'),
    path('<str:username>/posts/', UserPostListView.as_view(), name='user-posts'),
    path('five-latest-posts/', FiveLatestPostListView.as_view(), name='five-latest-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('about/', about_page, name='blog-about'),

]

post_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),

    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="users/logout.html"), name='logout'),
    path('profile/<str:username>/', user_views.profile, name='profile'),
    # password reset
    # path('password-reset/',
    #      auth_views.PasswordResetView.as_view(template_name="users/password_reset.html"),
    #      name='password-reset'),
    #
    # path('password-reset/done/',
    #      auth_views.PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
    #      name='password-reset-done'),
    #
    # path('password-reset/confirm/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
    #      name='password-reset-confirm')

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),

]
#
# if settings.DEBUG:  # It means if we are currently in DEBUG mode.
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={'pk': self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User

from PIL import Image

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return self.user.username

    # To resize our uploaded image while creating a profile or uploading an image
    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)  # This will open this profile image while we saved it

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

blog/forms.py
from django import forms

from .models import Post


# class PostForm(forms.ModelForm):
#     class Meta:
#         model = Post
#         fields = ['title', 'content']

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import Profile


class UserRegisterForm(UserCreationForm):  # User Registration Form
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):  # User Update Form
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):  # Update Profile Form
    class Meta:
        model = Profile
        fields = ['image']

blog/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from .models import Post


# from .forms import PostForm


def about_page(request):
    return render(request, 'blog/about.html')


class PostListView(ListView):
    model = Post
    template_name = 'blog/home_page.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5


class FiveLatestPostListView(ListView):
    model = Post
    template_name = 'blog/latest_posts.html'
    context_object_name = 'posts'
    queryset = Post.objects.all().order_by('-date_posted')[0:5]


class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']

    def test_func(self):
        post = self.get_object()  # this will return current post that we want to update
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    context_object_name = 'post'
    success_url = reverse_lazy('blog:blog-home')

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

users/views.py
from django.shortcuts import render, redirect
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages

from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=True)
            messages.success(request, f"Account created for [{user.username}].")
            login(request, user)
            return redirect('blog:blog-home')

    else:
        form = UserRegisterForm()

    context = {'form': form}
    return render(request, 'users/register.html', context)


@login_required(login_url='login')
def profile(request, username):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f"Your Account has been updated!")
            return redirect('profile',{'username':username})

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'users/profile.html', context)

blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block title %}ABOUT{% endblock title %}

{% block content %}
<h2>About this page:</h2>

{% endblock content %}

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">

    <title>
        Post Blog - {% block title %}{% endblock title %}
    </title>

</head>
<body>

<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'blog:blog-home' %}">Django Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'blog:blog-home' %}">Home</a>
                    <a class="nav-item nav-link" href="{% url 'blog:blog-about' %}">About</a>
                    {#                    <a class="nav-item nav-link" href="http://127.0.0.1:8000/admin/">ADMIN</a>#}
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if request.user.is_authenticated %}
                        <a class="nav-item nav-link"
                           href="{% url 'profile' request.user.username %}">{{ request.user.username }}</a>
                        <a class="nav-item nav-link" href="{% url 'blog:post-create' %}">Add-Post</a>
                        <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                        <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>


<main role="main" class="container">
    <div class="row">
        <div class="col-md-8">

            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}

            {% block content %}{% endblock content %}
        </div>
        <div class="col-md-4">
            <div class="content-section">
                <h3>Our Sidebar</h3>
                {#                <p class='text-muted'>You can put any information here you'd like.#}
                <ul class="list-group">
                    <li class="list-group-item list-group-item-light">
                        <a href="{% url 'blog:five-latest-posts' %}">Five Latest Posts</a>
                    </li>
                    {#                    <li class="list-group-item list-group-item-light">Announcements</li>#}
                    {#                    <li class="list-group-item list-group-item-light">Calendars</li>#}
                    {#                    <li class="list-group-item list-group-item-light">etc</li>#}
                </ul>
                </p>
            </div>
        </div>
    </div>
</main>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>


</body>
</html>

blog/templates/blog/home_page.html
{% extends 'blog/base.html' %}

{% block title %}HOME{% endblock title %}

{% block content %}

{% for post in posts %}
    <article class="media content-section">
        <img src="{{ post.author.profile.image.url }}" class="rounded-circle article-img">

        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{% url 'blog:user-posts' post.author.username %}">{{ post.author }}</a>
                <small class="text-muted">{{ post.date_posted|date:"f A - F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'blog:post-detail' post.pk %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
{% empty %}
    <h3>No Post Yet!</h3>
{% endfor %}

{% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}

{% endblock content %}

blog/templates/blog/latest_posts.html
{% extends 'blog/base.html' %}

{% block title %}5 Latest Posts{% endblock title %}

{% block content %}


    <h1 class="mb-3">Five Latest Posts:</h1>

    {% for post in posts %}
        <article class="media content-section">
            <img src="{{ post.author.profile.image.url }}" class="rounded-circle article-img">

            <div class="media-body">
                <div class="article-metadata">
                    <span class="mr-2">{{ post.author }}</span>
                    <small class="text-muted">{{ post.date_posted|date:"f A - F d, Y" }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'blog:post-detail' post.pk %}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% empty %}
        <h3>No Latest Post !</h3>
    {% endfor %}

{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}

{% block title %}Delete Post{% endblock title %}

{% block content %}

    <div class="content-section">
        <div class="content-section">
            <form method="post" action="">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Delete Post</legend>
                    <h4>Are you sure you want to delete this post ( {{ post.title }} )?!</h4>
                </fieldset>
                <div class="form-group">
                    <input type="submit" value="Yes I'm Sure" class="btn btn-danger">
                    <a class="btn btn-outline-secondary" href="{% url 'blog:post-detail' post.pk %}">Cancel</a>
                </div>
            </form>
        </div>

    </div>


{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block title %}{{ post.title }}{% endblock title %}

{% block content %}

    <article class="media content-section">
        <img src="{{ post.author.profile.image.url }}" class="rounded-circle article-img">

        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="#">{{ post.author }}</a>
                <small class="text-muted">{{ post.date_posted|date:"f A - F d, Y" }}</small>
                {% if request.user == post.author %}
                    <a class="btn btn-outline-danger btn-sm mt-1 mb-1 ml-3" href="{% url 'blog:post-delete' post.pk %}">Delete</a>
                    <a class="btn btn-outline-info btn-sm mt-1 mb-1" href="{% url 'blog:post-update' post.pk %}">Update</a>
                {% endif %}
            </div>
            <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>



{% endblock content %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Register{% endblock title %}

{% block content %}

    <div class="content-section">
        <form method="post" action="">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-outline-info">
                <a href="{% url 'blog:blog-home' %}" class="btn btn-outline-secondary">Cancel</a>
            </div>
        </form>
    </div>


{% endblock content %}

blog/templates/blog/user_posts.html
{% extends 'blog/base.html' %}

{% block title %}Posts By {{ view.kwargs.username }}{% endblock title %}

{% block content %}


    <h1 class="mb-3">Posts By {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>

    {% for post in posts %}
        <article class="media content-section">
            <img src="{{ post.author.profile.image.url }}" class="rounded-circle article-img">

            <div class="media-body">
                <div class="article-metadata">
                    <span class="mr-2">{{ post.author }}</span>
                    <small class="text-muted">{{ post.date_posted|date:"f A - F d, Y" }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'blog:post-detail' post.pk %}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% empty %}
        <h3>No Post Yet!</h3>
    {% endfor %}

    {% if is_paginated %}

        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}

{% endblock content %}

users/templates/users/login.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block title %}LOGIN{% endblock title %}

{% block content %}

    <div class="content-section">
        <form method="post" action="">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <input type="submit" value="Sign In" class="btn btn-outline-info">
                <small class="text-muted ml-2">
                    <a href="{% url 'password_reset' %}">Forgot Password ?!</a>
                </small>
            </div>

            <div class="border-top pt-3">
                <small class="text-muted">Don't have an account? <a href="{% url 'register' %}" class="ml-2">Sign Up Now</a></small>
            </div>

        </form>
    </div>

{% endblock content %}

users/templates/users/logout.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block title %}LOGOUT{% endblock title %}

{% block content %}

    <h3>You have been logged out!</h3>
    <div class="border-top pt-3">
        <a href="{% url 'login' %}">Login again</a>

    </div>


{% endblock content %}

users/templates/users/password_reset.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Password Reset{% endblock title %}

{% block content %}

    <div class="content-section">
        <form method="post" action="">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <input type="submit" value="Request Password Reset" class="btn btn-outline-info">
            </div>
        </form>
    </div>

{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="alert alert-success">
        Your password has been set.
    </div>
    <a href="{% url 'login' %}" class="ml-4">Sign In Here</a>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Password Reset Confirm{% endblock title %}

{% block content %}

    <div class="content-section">
        <form method="post" action="">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password Confirm</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <input type="submit" value="Confirm" class="btn btn-outline-info">
            </div>
        </form>
    </div>

{% endblock content %}

users/templates/users/password_reset_done.html
{% extends 'blog/base.html' %}

{% block title %}Password Reset Done{% endblock title %}

{% block content %}

    <div class="alert alert-info">
        An email has been sent with instructions to reset your password.
    </div>

{% endblock content %}

users/templates/users/profile.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block title %}{{ request.user.username }}{% endblock title %}


{% block content %}

    <div class="content-section">
        <div class="media">
            <div class="rounded-circle account-img-div">
                <img class="account-img" src="{{ user.profile.image.url }}">
            </div>
            <div class="media-body">
                <h2 class="account-heading">{{ user.username }}</h2>
                <p class="text-secondary">{{ user.email }}</p>
            </div>
        </div>

        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Info</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-outline-info">
            </div>
        </form>
    </div>

{% endblock content %}

users/templates/users/register.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Register{% endblock title %}

{% block content %}

    <div class="content-section">
        <form method="post" action="">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <input type="submit" value="Sign Up" class="btn btn-outline-info">
            </div>
        </form>
    </div>

    <div class="border-top pt-3">
        <small class="text-muted">
            Already have an account? <a href="{% url 'login' %}" class="ml-2">Login</a>
        </small>
    </div>

{% endblock content %}